Add long_description for PyPI
spotify/gordon-janitor-gcp pull request #27
Opened 2018-06-04 19:22 UTC by ocsw

**What this PR does / why we need it**:
Adds a long_description for PyPI.

**Which issue(s) this PR fixes**

Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Added a long_description for PyPI.
```

2018-06-04 19:22 UTC, ocsw commented
Hm.  Should I just use README instead?

2018-06-04 19:25 UTC, econchick requested changes

2018-06-04 19:25 UTC, econchick commented on setup.py
> +    long_description=read('DESCRIPTION.md'),
Could this just be the `README.rst`?

Perhaps not for this - if we do it for others - but we could also add the changelog, i.e. `read('README.rst', 'CHANGELOG.rst')`

2018-06-04 19:27 UTC, ocsw commented
https://stackoverflow.com/questions/16367770/my-rst-readme-is-not-formatted-on-pypi-python-org

Seems they do support it, more or less?

2018-06-04 19:42 UTC, ocsw commented
No, that's got repo stuff, not package stuff.

2018-06-04 19:43 UTC, ocsw commented
Er, didn't see your comment @econchick before I re-uploaded to fix the tests.  Let's discuss.

2018-06-04 20:17 UTC, econchick commented
PyPI always has had rst support, IIRC they just added markdown support.

rst is very common to use for descriptions, even if it isn't parsed "prettily." @ocsw people still do, though (eg [ex1](https://github.com/spotify/ramlfications/blob/master/setup.py#L55) ([rendered](https://pypi.org/project/ramlfications/)), [ex2](https://github.com/python-attrs/attrs/blob/master/setup.py#L81-L90) ([rendered](https://pypi.org/project/attrs/)))

2018-06-04 20:29 UTC, matt0bi commented on setup.py
> +    long_description=read('DESCRIPTION.md'),
Just talked IRL about this with @ocsw  - we settled on using `README.rst` for the `long_description` as the simplest, most legible approach.

2018-06-04 20:44 UTC, ocsw commented
@econchick changed to your suggestion

2018-06-04 23:00 UTC, descent3me commented
LGTM +1

2018-06-05 14:32 UTC, econchick approved these changes

2018-06-05 16:18 UTC, merged